// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbkgdvrnuyitorpaafog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNia2dkdnJudXlpdG9ycGFhZm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1Njc1MTMsImV4cCI6MjA1MTE0MzUxM30.3-GCw1YBJ-Quqyk6wOEolylM3of7V_2u_0sNQHWzP6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);